# Day 1 of ML 30-Days Challenge

# Task
NumPy Mastery: Learn array manipulation, indexing, and mathematical operations with NumPy.
- Beginner Level
- Intermidiate Level
- Master Level

## Numpy arrays


In [55]:
import numpy as np

# 1. Create a 1-dimensional NumPy array from a Python list.
python_list = [1, 2, 3, 4, 5]
numpy_array_1d = np.array(python_list)
print("1-D Array from List:")
display(numpy_array_1d)

1-D Array from List:


array([1, 2, 3, 4, 5])

In [56]:
# 2. Create a 2-dimensional NumPy array from a nested Python list.
nested_python_list = [[1, 2, 3], [4, 5, 6]]
numpy_array_2d = np.array(nested_python_list)
print("\n2-D Array from Nested List:")
display(numpy_array_2d)


2-D Array from Nested List:


array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
# 3. Create a NumPy array filled with zeros, with a specified shape.
zeros_array = np.zeros((3, 4))
print("\nArray of Zeros (3x4):")
display(zeros_array)


Array of Zeros (3x4):


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
# 4. Create a NumPy array filled with ones, with a specified shape.
ones_array = np.ones((2, 3))
print("\nArray of Ones (2x3):")
display(ones_array)


Array of Ones (2x3):


array([[1., 1., 1.],
       [1., 1., 1.]])

In [59]:
# 5. Create a NumPy array with a range of values, similar to Python's `range`.
range_array = np.arange(10)
print("\nArray from Range (0 to 9):")
display(range_array)


Array from Range (0 to 9):


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
# 6. Create a NumPy array with values spaced evenly over a specified interval.
linspace_array = np.linspace(0, 10, 5) # 5 values between 0 and 10 (inclusive)
print("\nArray with Evenly Spaced Values (5 values from 0 to 10):")
display(linspace_array)


Array with Evenly Spaced Values (5 values from 0 to 10):


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [61]:
# 7. Reshape a 1-dimensional array into a 2-dimensional array.
reshaped_array = np.arange(12).reshape((3, 4))
print("\nReshaped 1-D Array (12 elements reshaped to 3x4):")
display(reshaped_array)


Reshaped 1-D Array (12 elements reshaped to 3x4):


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
# 8. Flatten a 2-dimensional array back into a 1-dimensional array.
flattened_array = reshaped_array.flatten()
print("\nFlattened 2-D Array:")
display(flattened_array)


Flattened 2-D Array:


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [63]:
# 9. Index a single element in a 1-dimensional array.
element_1d = numpy_array_1d[2]
print("\nSingle element from 1-D array (index 2):")
display(element_1d)


Single element from 1-D array (index 2):


np.int64(3)

In [64]:
# 10. Index a single element in a 2-dimensional array using row and column indices.
element_2d = numpy_array_2d[1, 2] # Row 1, Column 2
print("\nSingle element from 2-D array (row 1, column 2):")
display(element_2d)


Single element from 2-D array (row 1, column 2):


np.int64(6)

In [65]:
# 11. Slice a portion of a 1-dimensional array.
sliced_1d = numpy_array_1d[1:4] # Elements from index 1 up to (but not including) index 4
print("\nSliced 1-D array (indices 1 to 3):")
display(sliced_1d)


Sliced 1-D array (indices 1 to 3):


array([2, 3, 4])

In [66]:
# 12. Slice a portion of a 2-dimensional array to select rows and columns.
sliced_2d = numpy_array_2d[0:2, 1:3] # Rows 0 and 1, Columns 1 and 2
print("\nSliced 2-D array (rows 0-1, columns 1-2):")
display(sliced_2d)


Sliced 2-D array (rows 0-1, columns 1-2):


array([[2, 3],
       [5, 6]])

In [67]:
# 13. Use boolean indexing to select elements from an array based on a condition.
boolean_indexed_array = numpy_array_1d[numpy_array_1d > 3] # Elements greater than 3
print("\nBoolean indexed 1-D array (elements > 3):")
display(boolean_indexed_array)


Boolean indexed 1-D array (elements > 3):


array([4, 5])

In [68]:
# 14. Use fancy indexing to select elements from an array using a list or array of indices.
fancy_indexed_array = numpy_array_1d[[0, 4, 2]] # Elements at indices 0, 4, and 2
print("\nFancy indexed 1-D array (elements at indices 0, 4, 2):")
display(fancy_indexed_array)


Fancy indexed 1-D array (elements at indices 0, 4, 2):


array([1, 5, 3])

## Numpy Data Types

In [69]:
# 1. Create a NumPy array with a specified integer dtype and display it along with its dtype.
int_array = np.array([10, 20, 30], dtype=np.int32)
print("\nCreating an array with a specified integer dtype (np.int32):")
print(f"The array is: {int_array}")
print(f"The dtype of the array is: {int_array.dtype}")


Creating an array with a specified integer dtype (np.int32):
The array is: [10 20 30]
The dtype of the array is: int32


In [70]:
# 2. Create a NumPy array with a specified float dtype and display it along with its dtype.
float_array = np.array([1.1, 2.2, 3.3], dtype=np.float64)
print("\nCreating an array with a specified float dtype (np.float64):")
print(f"The array is: {float_array}")
print(f"The dtype of the array is: {float_array.dtype}")


Creating an array with a specified float dtype (np.float64):
The array is: [1.1 2.2 3.3]
The dtype of the array is: float64


In [71]:
# 3. Create a NumPy array with a specified boolean dtype and display it along with its dtype.
bool_array = np.array([True, False, True], dtype=np.bool_)
print("\nCreating an array with a specified boolean dtype (np.bool_):")
print(f"The array is: {bool_array}")
print(f"The dtype of the array is: {bool_array.dtype}")


Creating an array with a specified boolean dtype (np.bool_):
The array is: [ True False  True]
The dtype of the array is: bool


In [72]:
# 4. Create a NumPy array with a specified string dtype and display it along with its dtype.
string_array = np.array(['apple', 'banana', 'cherry'], dtype=np.str_)
print("\nCreating an array with a specified string dtype (np.str_):")
print(f"The array is: {string_array}")
print(f"The dtype of the array is: {string_array.dtype}")


Creating an array with a specified string dtype (np.str_):
The array is: ['apple' 'banana' 'cherry']
The dtype of the array is: <U6


## Numpy array operations


In [73]:
import numpy as np

# 1. Describe and demonstrate element-wise operations
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

print("\nArray 1:", array1)
print("Array 2:", array2)

print("\nElement-wise Addition (Array 1 + Array 2):")
display(array1 + array2)

print("\nElement-wise Subtraction (Array 1 - Array 2):")
display(array1 - array2)

print("\nElement-wise Multiplication (Array 1 * Array 2):")
display(array1 * array2)

print("\nElement-wise Division (Array 1 / Array 2):")
display(array1 / array2)


Array 1: [1 2 3 4]
Array 2: [5 6 7 8]

Element-wise Addition (Array 1 + Array 2):


array([ 6,  8, 10, 12])


Element-wise Subtraction (Array 1 - Array 2):


array([-4, -4, -4, -4])


Element-wise Multiplication (Array 1 * Array 2):


array([ 5, 12, 21, 32])


Element-wise Division (Array 1 / Array 2):


array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [74]:
# 2. Describe and demonstrate broadcasting with a scalar
scalar = 10
print("\nArray 1:", array1)
print("Scalar:", scalar)
print("\nBroadcasting with Scalar (Array 1 + Scalar):")
display(array1 + scalar)


Array 1: [1 2 3 4]
Scalar: 10

Broadcasting with Scalar (Array 1 + Scalar):


array([11, 12, 13, 14])

In [75]:
# 3. Describe and demonstrate broadcasting with arrays of different shapes
array3 = np.array([[1, 2, 3], [4, 5, 6]])
array4 = np.array([10, 20, 30])

print("\nArray 3 (Shape (2, 3)):")
display(array3)
print("Array 4 (Shape (3,)):")
display(array4)
print("\nBroadcasting with Arrays of Different Shapes (Array 3 + Array 4):")
display(array3 + array4)


Array 3 (Shape (2, 3)):


array([[1, 2, 3],
       [4, 5, 6]])

Array 4 (Shape (3,)):


array([10, 20, 30])


Broadcasting with Arrays of Different Shapes (Array 3 + Array 4):


array([[11, 22, 33],
       [14, 25, 36]])

In [76]:
# 4. Describe and demonstrate matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

print("\nMatrix 1:", matrix1)
print("Matrix 2:", matrix2)

print("\nMatrix Multiplication (Matrix 1 @ Matrix 2):")
display(matrix1 @ matrix2)


Matrix 1: [[1 2]
 [3 4]]
Matrix 2: [[5 6]
 [7 8]]

Matrix Multiplication (Matrix 1 @ Matrix 2):


array([[19, 22],
       [43, 50]])

In [77]:
# 5. Describe and demonstrate dot product of two vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

print("\nVector 1:", vector1)
print("Vector 2:", vector2)

print("\nDot Product of Vectors (np.dot(Vector 1, Vector 2)):")
display(np.dot(vector1, vector2))


Vector 1: [1 2 3]
Vector 2: [4 5 6]

Dot Product of Vectors (np.dot(Vector 1, Vector 2)):


np.int64(32)

## Numpy mathematical functions


In [78]:
import numpy as np

# 1. Create a NumPy array and demonstrate several common universal functions
array_ufunc = np.array([0, np.pi/2, np.pi, 2*np.pi])
print("\nOriginal array for ufuncs:", array_ufunc)

print("\nApplying common universal functions:")
print("np.sin(array_ufunc):")
display(np.sin(array_ufunc))

print("np.cos(array_ufunc):")
display(np.cos(array_ufunc))

print("np.exp(array_ufunc):")
display(np.exp(array_ufunc))

print("np.sqrt(np.array([1, 4, 9, 16])):") # Using a different array for sqrt demonstration
display(np.sqrt(np.array([1, 4, 9, 16])))

print("np.log(np.array([1, np.exp(1), np.exp(2)])):") # Using a different array for log demonstration
display(np.log(np.array([1, np.exp(1), np.exp(2)])))


Original array for ufuncs: [0.         1.57079633 3.14159265 6.28318531]

Applying common universal functions:
np.sin(array_ufunc):


array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -2.4492936e-16])

np.cos(array_ufunc):


array([ 1.000000e+00,  6.123234e-17, -1.000000e+00,  1.000000e+00])

np.exp(array_ufunc):


array([  1.        ,   4.81047738,  23.14069263, 535.49165552])

np.sqrt(np.array([1, 4, 9, 16])):


array([1., 2., 3., 4.])

np.log(np.array([1, np.exp(1), np.exp(2)])):


array([0., 1., 2.])

In [79]:
# 2. Describe and demonstrate other useful mathematical operations
array_math = np.array([10, 20, 30, 40, 50])
print("\nOriginal array for math operations:", array_math)

print("\nApplying common mathematical operations:")
print("np.sum(array_math):")
display(np.sum(array_math))

print("np.mean(array_math):")
display(np.mean(array_math))

print("np.std(array_math):")
display(np.std(array_math))

print("np.max(array_math):")
display(np.max(array_math))

print("np.min(array_math):")
display(np.min(array_math))


Original array for math operations: [10 20 30 40 50]

Applying common mathematical operations:
np.sum(array_math):


np.int64(150)

np.mean(array_math):


np.float64(30.0)

np.std(array_math):


np.float64(14.142135623730951)

np.max(array_math):


np.int64(50)

np.min(array_math):


np.int64(10)

In [80]:
# 3. Demonstrate how to apply these mathematical operations along a specific axis
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nOriginal 2D array:")
display(array_2d)

print("\nApplying operations along a specific axis:")
print("np.sum(array_2d, axis=0) (Sum along columns):")
display(np.sum(array_2d, axis=0)) # Sum of each column

print("np.sum(array_2d, axis=1) (Sum along rows):")
display(np.sum(array_2d, axis=1)) # Sum of each row

print("np.mean(array_2d, axis=0) (Mean along columns):")
display(np.mean(array_2d, axis=0)) # Mean of each column

print("np.max(array_2d, axis=1) (Max along rows):")
display(np.max(array_2d, axis=1)) # Maximum value in each row


Original 2D array:


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


Applying operations along a specific axis:
np.sum(array_2d, axis=0) (Sum along columns):


array([12, 15, 18])

np.sum(array_2d, axis=1) (Sum along rows):


array([ 6, 15, 24])

np.mean(array_2d, axis=0) (Mean along columns):


array([4., 5., 6.])

np.max(array_2d, axis=1) (Max along rows):


array([3, 6, 9])

## Numpy random number generation


In [81]:
# 1. Generate a single random float between 0.0 and 1.0
print("\nGenerating a single random float between 0.0 and 1.0:")
single_float = np.random.rand()
display(single_float)


Generating a single random float between 0.0 and 1.0:


0.15599452033620265

In [82]:
# 2. Generate an array of random floats between 0.0 and 1.0
print("\nGenerating an array of random floats (2x3) between 0.0 and 1.0:")
float_array = np.random.rand(2, 3)
display(float_array)


Generating an array of random floats (2x3) between 0.0 and 1.0:


array([[0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985]])

In [83]:
# 3. Generate a single random integer within a specified range
print("\nGenerating a single random integer between 1 and 10 (inclusive):")
single_int = np.random.randint(1, 11) # High value is exclusive, so 11 to include 10
display(single_int)


Generating a single random integer between 1 and 10 (inclusive):


6

In [84]:
# 4. Generate an array of random integers within a specified range and shape
print("\nGenerating an array of random integers (3x3) between 5 and 20 (inclusive):")
int_array = np.random.randint(5, 21, size=(3, 3)) # High value is exclusive, so 21 to include 20
display(int_array)


Generating an array of random integers (3x3) between 5 and 20 (inclusive):


array([[ 6, 20, 16],
       [ 9,  5, 16],
       [14, 10, 17]])

In [85]:
# 5. Generate a single random number from a standard normal distribution
print("\nGenerating a single random number from a standard normal distribution (mean 0, variance 1):")
single_normal = np.random.randn()
display(single_normal)


Generating a single random number from a standard normal distribution (mean 0, variance 1):


-1.7249178325130328

In [86]:
# 6. Generate an array of random numbers from a standard normal distribution
print("\nGenerating an array of random numbers (2x4) from a standard normal distribution:")
normal_array = np.random.randn(2, 4)
display(normal_array)


Generating an array of random numbers (2x4) from a standard normal distribution:


array([[-0.56228753, -1.01283112,  0.31424733, -0.90802408],
       [-1.4123037 ,  1.46564877, -0.2257763 ,  0.0675282 ]])

In [87]:
# 7. Describe the importance of setting a seed and demonstrate
seed_value = 42
np.random.seed(seed_value)
print(f"\nSetting seed to {seed_value} and generating random numbers:")

# Generate some random numbers after setting the seed
random_after_seed1 = np.random.rand(5)
display(random_after_seed1)

# Let's demonstrate by generating another set of random numbers in the same run:
print("\nGenerating another set of random numbers after setting the seed:")
random_after_seed2 = np.random.rand(5)
display(random_after_seed2)

# To show reproducibility, you would typically re-run the code from the seed setting line.
np.random.seed(seed_value)
print(f"\nResetting seed to {seed_value} and generating the first set again:")
random_after_seed_reset = np.random.rand(5)
display(random_after_seed_reset) # This array should be identical to random_after_seed1


Setting seed to 42 and generating random numbers:


array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])


Generating another set of random numbers after setting the seed:


array([0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])


Resetting seed to 42 and generating the first set again:


array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

## Numpy i/o

In [88]:
import numpy as np
import os

# 1. Create a sample NumPy array to be used for saving.
sample_array = np.arange(12).reshape(3, 4)
print("\nCreated a sample NumPy array to save:")
display(sample_array)


Created a sample NumPy array to save:


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
# 2. Save the created array to a file named my_array.npy using np.save.
file_name = 'my_array.npy'
np.save(file_name, sample_array)
print(f"\nSample array saved to '{file_name}'")


Sample array saved to 'my_array.npy'


In [90]:
# 3. Describe the format of .npy files.
print("\nDescription of .npy files:")


Description of .npy files:


In [91]:
# 5. Load the saved array from my_array.npy back into a new variable using np.load.
loaded_array = np.load(file_name)
print(f"\nLoaded array from '{file_name}':")
display(loaded_array)


Loaded array from 'my_array.npy':


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
# 6. Display the loaded array to verify it matches the original array.
print("\nVerification:")
if np.array_equal(sample_array, loaded_array):
    print("The loaded array matches the original array.")
else:
    print("The loaded array DOES NOT match the original array.")


Verification:
The loaded array matches the original array.


## Advanced numpy topics

In [93]:
import numpy as np
import os

# 1. Create a sample NumPy array and demonstrate fancy indexing using a list or array of indices.
fancy_array = np.array([10, 20, 30, 40, 50, 60, 70, 80])
indices = [0, 3, 6, 2]
print("\nOriginal array for fancy indexing:", fancy_array)
print("Indices for fancy indexing:", indices)
print("Array elements at specified indices:")
display(fancy_array[indices])

# Demonstrate with a 2D array
fancy_array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
row_indices = [0, 2, 1]
col_indices = [2, 0]
print("\nOriginal 2D array for fancy indexing:")
display(fancy_array_2d)
print("Selecting specific rows using indices:", row_indices)
display(fancy_array_2d[row_indices])
# Note: Combining row and column fancy indexing can be more complex and requires pairing indices or using open indexing. Simple example:
print("Selecting specific elements using paired row and column indices:")
display(fancy_array_2d[[0, 2, 3], [2, 1, 0]]) # Selects (0,2), (2,1), and (3,0)


Original array for fancy indexing: [10 20 30 40 50 60 70 80]
Indices for fancy indexing: [0, 3, 6, 2]
Array elements at specified indices:


array([10, 40, 70, 30])


Original 2D array for fancy indexing:


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Selecting specific rows using indices: [0, 2, 1]


array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

Selecting specific elements using paired row and column indices:


array([ 3,  8, 10])

In [94]:
# 2. Create a sample structured array with fields for name, age, and height, and display it.
# Define the data type
dtype = [('name', 'S10'), ('age', 'i4'), ('height', 'f8')]
# Create the structured array
structured_array = np.array([
    ('Alice', 30, 1.65),
    ('Bob', 25, 1.80),
    ('Charlie', 35, 1.75)
], dtype=dtype)
print("\nSample structured array:")
display(structured_array)


Sample structured array:


array([(b'Alice', 30, 1.65), (b'Bob', 25, 1.8 ), (b'Charlie', 35, 1.75)],
      dtype=[('name', 'S10'), ('age', '<i4'), ('height', '<f8')])

In [95]:
# 3. Demonstrate accessing data in the structured array using field names.
print("\nAccessing data in the structured array:")
print("Names:", structured_array['name'])
print("Ages:", structured_array['age'])
print("Heights:", structured_array['height'])
print("First element's age:", structured_array[0]['age'])


Accessing data in the structured array:
Names: [b'Alice' b'Bob' b'Charlie']
Ages: [30 25 35]
Heights: [1.65 1.8  1.75]
First element's age: 30


In [96]:
# 4. Create a large sample array and save it to a memory-mapped file using np.memmap.
memmap_filename = 'large_array.mmap'
shape = (1000, 1000)
dtype_memmap = np.float64

# Create and initialize the memory-mapped array
large_array_memmap = np.memmap(memmap_filename, dtype=dtype_memmap, mode='w+', shape=shape)

# Initialize with some values (e.g., a range)
for i in range(shape[0]):
    large_array_memmap[i, :] = np.arange(shape[1]) * (i + 1) # Assign values row by row

# Explicitly flush changes to disk (optional but good practice)
large_array_memmap.flush()
print(f"\nCreated and initialized a memory-mapped array of shape {shape} saved to '{memmap_filename}'")


Created and initialized a memory-mapped array of shape (1000, 1000) saved to 'large_array.mmap'


In [97]:
# 5. Access and modify elements of the memory-mapped array without loading the entire array into memory.
# Accessing elements
print("\nAccessing elements from the memory-mapped array:")
print("Element at (0, 0):", large_array_memmap[0, 0])
print("Element at (100, 500):", large_array_memmap[100, 500])

# Modifying elements
print("\nModifying an element in the memory-mapped array:")
print("Original element at (10, 10):", large_array_memmap[10, 10])
large_array_memmap[10, 10] = 999.99
print("Modified element at (10, 10):", large_array_memmap[10, 10])

# Changes are automatically written back to the file, but flushing ensures they are on disk immediately.
large_array_memmap.flush()
print("Changes flushed to disk.")

# You can also slice the memmap array. This accesses a portion without loading the whole thing.
print("\nAccessing a slice from the memory-mapped array (rows 0-2, columns 0-5):")
display(large_array_memmap[0:3, 0:6])


Accessing elements from the memory-mapped array:
Element at (0, 0): 0.0
Element at (100, 500): 50500.0

Modifying an element in the memory-mapped array:
Original element at (10, 10): 110.0
Modified element at (10, 10): 999.99
Changes flushed to disk.

Accessing a slice from the memory-mapped array (rows 0-2, columns 0-5):


memmap([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 0.,  2.,  4.,  6.,  8., 10.],
        [ 0.,  3.,  6.,  9., 12., 15.]])

In [98]:
# 6. Close or delete the memory-mapped file to clean up resources.
# Delete the memmap object to close the file handle
del large_array_memmap
print("\nDeleted memory-mapped array object.")

# Remove the file from the filesystem
if os.path.exists(memmap_filename):
    os.remove(memmap_filename)
    print(f"Removed memory-mapped file '{memmap_filename}'")


Deleted memory-mapped array object.
Removed memory-mapped file 'large_array.mmap'
